### ISSUE TITLE
"New File" button makes it crash.

### ISSUE THREAD

**Issue by gustavklopp** [ktechlab/ktechlab#54]
**How to reproduce:**
Launch ktechlab
Click on the button "New File" (not on the right triangle).
The program crashes.
**Config:**
Arch Linux
Ktechlab Build version

**Error message:**
```
$ ./run-simple.sh 
+ case "$(uname -s)" in
++ uname -s
+ echo Linux
Linux
+++ readlink -f ./run-simple.sh
++ dirname /home/klopp/Documents/ktechlab/run-simple.sh
+ SCRIPTDIR=/home/klopp/Documents/ktechlab
+ export PATH=/home/klopp/Documents/ktechlab/inst-simple/bin:/home/klopp/Documents:/home/klopp/backup_ln/PROGRAMS/ANDROID/.repo:/home/klopp/backup_ln/PROGRAMS/ANDROID/lineageOS:/home/klopp/backup_ln/PROGRAMS/ANDROID/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+ PATH=/home/klopp/Documents/ktechlab/inst-simple/bin:/home/klopp/Documents:/home/klopp/backup_ln/PROGRAMS/ANDROID/.repo:/home/klopp/backup_ln/PROGRAMS/ANDROID/lineageOS:/home/klopp/backup_ln/PROGRAMS/ANDROID/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+ /home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab
Starting logging to  "/tmp/ktechlab-pid-20730-log"
(WW) Icon theme "Vibrancy-Full-Dark-Teal" not found.
(WW) void ItemLibrary::loadItemDescriptions() Could not open file " "/usr/local/share/ktechlab/contexthelp/help-English" " 

(WW) Icon theme "Vibrancy-Full-Dark-Teal" not found.
(WW) QObject::connect: No such signal KHTMLPartBrowserExtension::openUrlRequest( const KUrl &, const KParts::OpenUrlArguments & )
(WW) QObject::connect:  (sender name:   'KHTMLBrowserExtension')
(WW) QObject::connect:  (receiver name: 'ContextHelpWidget')
(WW) KXMLGUI file found at deprecated location ("/usr/local/share/ktechlab/ktechlabui.rc") -- please use ${KXMLGUI_INSTALL_DIR} to install this file instead.
(WW) KXMLGUI file found at deprecated location ("/usr/local/share/ktechlab/ktechlabui.rc") -- please use ${KXMLGUI_INSTALL_DIR} to install this file instead.
(Critical) Shortcut for action  "file_new" "New File" set with QAction::setShortcut()! Use KActionCollection::setDefaultShortcut(s) instead.
(WW) KXMLGUI file found at deprecated location ("/usr/local/share/ktechlab/ktechlabitemviewui.rc") -- please use ${KXMLGUI_INSTALL_DIR} to install this file instead.
(WW) KXMLGUI file found at deprecated location ("/usr/local/share/ktechlab/ktechlabcircuitui.rc") -- please use ${KXMLGUI_INSTALL_DIR} to install this file instead.
=================================================================
==20730==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200013a4a0 at pc 0x55ce5cc6307d bp 0x7ffe272c00a0 sp 0x7ffe272c0090
READ of size 4 at 0x60200013a4a0 thread T0
    #0 0x55ce5cc6307c in QSize::width() const (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x2e107c)
    #1 0x55ce5cce591d in NewFileDlg::NewFileDlg(QWidget*) (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x36391d)
    #2 0x55ce5d0cbb47 in KTechlab::slotFileNew() (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x749b47)
    #3 0x55ce5cc23fc0 in KTechlab::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x2a1fc0)
    #4 0x7f22cad82a10 in QMetaObject::activate(QObject*, int, int, void**) (/usr/lib/libQt5Core.so.5+0x2bba10)
    #5 0x7f22cb996e92 in QAction::triggered(bool) (/usr/lib/libQt5Widgets.so.5+0x152e92)
    #6 0x7f22cb999623 in QAction::activate(QAction::ActionEvent) (/usr/lib/libQt5Widgets.so.5+0x155623)
    #7 0x7f22cba97c2c  (/usr/lib/libQt5Widgets.so.5+0x253c2c)
    #8 0x7f22cba97e55 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) (/usr/lib/libQt5Widgets.so.5+0x253e55)
    #9 0x7f22cbb8ccea in QToolButton::mouseReleaseEvent(QMouseEvent*) (/usr/lib/libQt5Widgets.so.5+0x348cea)
    #10 0x7f22cb9e0cb5 in QWidget::event(QEvent*) (/usr/lib/libQt5Widgets.so.5+0x19ccb5)
    #11 0x7f22cbb8cd94 in QToolButton::event(QEvent*) (/usr/lib/libQt5Widgets.so.5+0x348d94)
    #12 0x7f22cb99d4d4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x1594d4)
    #13 0x7f22cb9a6c6b in QApplication::notify(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x162c6b)
    #14 0x7f22cad569c1 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/usr/lib/libQt5Core.so.5+0x28f9c1)
    #15 0x7f22cb9a5d4a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (/usr/lib/libQt5Widgets.so.5+0x161d4a)
    #16 0x7f22cb9fd210  (/usr/lib/libQt5Widgets.so.5+0x1b9210)
    #17 0x7f22cba00153  (/usr/lib/libQt5Widgets.so.5+0x1bc153)
    #18 0x7f22cb99d4d4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x1594d4)
    #19 0x7f22cb9a6a20 in QApplication::notify(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x162a20)
    #20 0x7f22cad569c1 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/usr/lib/libQt5Core.so.5+0x28f9c1)
    #21 0x7f22cb366788 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (/usr/lib/libQt5Gui.so.5+0x121788)
    #22 0x7f22cb36805a in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (/usr/lib/libQt5Gui.so.5+0x12305a)
    #23 0x7f22cb34037b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Gui.so.5+0xfb37b)
    #24 0x7f22bfffbfeb  (/usr/lib/libQt5XcbQpa.so.5+0x6bfeb)
    #25 0x7f22cce5f90e in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x6b90e)
    #26 0x7f22cce61868  (/usr/lib/libglib-2.0.so.0+0x6d868)
    #27 0x7f22cce618ad in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x6d8ad)
    #28 0x7f22cadae9a2 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Core.so.5+0x2e79a2)
    #29 0x7f22cad555eb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Core.so.5+0x28e5eb)
    #30 0x7f22cad5d325 in QCoreApplication::exec() (/usr/lib/libQt5Core.so.5+0x296325)
    #31 0x55ce5cc3d52d in main (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x2bb52d)
    #32 0x7f22ca5e2ee2 in __libc_start_main (/usr/lib/libc.so.6+0x26ee2)
    #33 0x55ce5cc06bfd in _start (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x284bfd)

0x60200013a4a0 is located 0 bytes to the right of 16-byte region [0x60200013a490,0x60200013a4a0)
allocated by thread T0 here:
    #0 0x7f22ce2e0ada in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f22cabdf1fd in QListData::detach(int) (/usr/lib/libQt5Core.so.5+0x1181fd)
    #2 0x7ffe272c06cf  ([stack]+0x1c6cf)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/klopp/Documents/ktechlab/inst-simple/bin/ktechlab+0x2e107c) in QSize::width() const
Shadow bytes around the buggy address:
  0x0c048001f440: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048001f450: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048001f460: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048001f470: fa fa fd fd fa fa 00 00 fa fa fd fd fa fa fd fd
  0x0c048001f480: fa fa fd fd fa fa fd fd fa fa 00 07 fa fa fd fd
=>0x0c048001f490: fa fa 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001f4a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001f4b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001f4c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001f4d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048001f4e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==20730==ABORTING
```

**Comment by zoltanp** [comment]
Should be fixed in latest master branch.
